### ISSUE TITLE
Which version of the sources should be worked on?

### ISSUE THREAD

**Issue by ctrlcctrlv** [geraldholdsworth/SpriteToBitmap#1]
I see both Delphi and Lazarus sources. I've only been able to get to edit the Lazarus sources as I don't own a copy of Delphi. Are these sources to be used in place of the Delphi ones, and the Delphi ones historical?

**Comment by geraldholdsworth** [comment]
Yes, the Delphi version is historical. The Lazarus version is the latest.

**Comment by ctrlcctrlv** [comment]
Thank you :-)
